services:
  # --- 1. SERVIDOR DE DADOS (PostgreSQL) ---
  wms-db-main:
    image: postgres:16-alpine
    container_name: wms-db-main
    environment:
      POSTGRES_USER: wms_user
      POSTGRES_PASSWORD: wms_password
      POSTGRES_DB: postgres
      TZ: America/Sao_Paulo
    volumes:
      - wms_main_data:/var/lib/postgresql/data
      - ./docker/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    ports:
      - "5432:5432"
    networks:
      - wms-network
    restart: always
    command: postgres -c 'max_connections=200'
    # CORREÇÃO 1: Adicionado "-d postgres" para não buscar o banco "wms_user"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wms_user -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- 2. SERVIDOR DE AUDITORIA (MongoDB) ---
  wms-mongo:
    image: mongo:7.0
    container_name: wms-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      MONGO_INITDB_DATABASE: wms_audit_global
      TZ: America/Sao_Paulo
    volumes:
      - wms_mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - wms-network
    restart: always
    # CORREÇÃO 2: Adicionado autenticação ao Healthcheck
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --username admin --password mongo_password --authenticationDatabase admin --quiet
      interval: 5s
      timeout: 5s
      retries: 10

  # --- 3. BACKEND (Spring Boot) ---
  wms-backend:
    build:
      context: ./wms-backend
      dockerfile: Dockerfile
    container_name: wms-backend-prod
    depends_on:
      wms-db-main:
        condition: service_healthy 
      wms-mongo:
        condition: service_healthy 
    environment:
      TZ: America/Sao_Paulo

      SPRING_DATASOURCE_URL: jdbc:postgresql://wms-db-main:5432/wms_master
      SPRING_DATASOURCE_USERNAME: wms_user
      SPRING_DATASOURCE_PASSWORD: wms_password
      
      # Garanta que a URI está EXATAMENTE assim (wms-mongo)
      SPRING_DATA_MONGODB_HOST: wms-mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: wms_audit_global
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: mongo_password
      

      JAVA_TOOL_OPTIONS: "-Dspring.data.mongodb.uri=mongodb://admin:mongo_password@wms-mongo:27017/wms_audit_global?authSource=admin"

      API_SECURITY_TOKEN_SECRET: "chave_super_secreta_wms_enterprise_2025"
    ports:
      - "8080:8080"
    networks:
      - wms-network
    restart: on-failure

  # --- 4. FRONTEND ---
  wms-frontend:
    build:
      context: ./wms-frontend
      dockerfile: Dockerfile
    container_name: wms-frontend-prod
    environment:
      TZ: America/Sao_Paulo
    depends_on:
      - wms-backend
    ports:
      - "80:80"
    networks:
      - wms-network
    restart: always

volumes:
  wms_main_data:
  wms_mongo_data:

networks:
  wms-network:
    driver: bridge