services:
  # --- 1. SERVIDOR DE DADOS (PostgreSQL) ---
  wms-db-main:
    image: postgres:16-alpine
    container_name: wms-db-main
    environment:
      POSTGRES_USER: wms_user
      POSTGRES_PASSWORD: wms_password
      POSTGRES_DB: postgres
    volumes:
      - wms_main_data:/var/lib/postgresql/data
      - ./docker/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    ports:
      - "5432:5432"
    networks:
      - wms-network
    restart: always
    command: postgres -c 'max_connections=200'
    # Healthcheck para o Postgres também
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wms_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- 2. SERVIDOR DE AUDITORIA (MongoDB) ---
  wms-mongo:
    image: mongo:7.0
    container_name: wms-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    volumes:
      - wms_mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - wms-network
    restart: always
    # --- A MÁGICA ESTÁ AQUI ---
    # Testa se o Mongo está respondendo ping
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 10

  # --- 3. BACKEND (Spring Boot) ---
  wms-backend:
    build:
      context: ./wms-backend
      dockerfile: Dockerfile
    container_name: wms-backend-prod
    depends_on:
      wms-db-main:
        condition: service_healthy # Espera o Postgres estar PRONTO
      wms-mongo:
        condition: service_healthy # Espera o Mongo estar PRONTO
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://wms-db-main:5432/wms_master
      SPRING_DATASOURCE_USERNAME: wms_user
      SPRING_DATASOURCE_PASSWORD: wms_password
      
      # Garanta que a URI está EXATAMENTE assim (wms-mongo)
      SPRING_DATA_MONGODB_URI: mongodb://admin:mongo_password@wms-mongo:27017/wms_audit_global?authSource=admin

      API_SECURITY_TOKEN_SECRET: "chave_super_secreta_wms_enterprise_2025"
    ports:
      - "8080:8080"
    networks:
      - wms-network
    restart: on-failure

  # --- 4. FRONTEND ---
  wms-frontend:
    build:
      context: ./wms-frontend
      dockerfile: Dockerfile
    container_name: wms-frontend-prod
    depends_on:
      - wms-backend
    ports:
      - "80:80"
    networks:
      - wms-network
    restart: always

volumes:
  wms_main_data:
  wms_mongo_data:

networks:
  wms-network:
    driver: bridge